### ISSUE TITLE
Calculated fields with currency actual type

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#104]
While testing the filters functionality for the new RB_Filters module noticed that system does not handle correctly filtering of `calculated` field types where actual type is `currency`.
For the `currency` fields QueryBuilder uses CAST for the SQL comparison while for the `calculated` field it uses the standard string. The filtered amount is therefore not correctly compared to the amount stored in database and filter results are wrong.

**Comment by bukowskiadam** [comment]
I've fixed this in dev branch. Please test it.

**Comment by georgehristov** [comment]
I will test and let you know but question is if this will not be the case also for other calculated field types that have values stored in the database.
In the RB_Filters module I added a method `get_field_type` that identifies the actual field type. Will that not be necessary here?

**Comment by bukowskiadam** [comment]
I've searched for any other usages - calculated field with a) number/integer b) date/timestamp and haven't found any.

In fact style is set even to other fields like integer. It's not intuitive that calculated field with style set should behave as such field. Style meant to be something else than type. We'll fix this during RB refactor - I wouldn't bother with this right now.

**Comment by georgehristov** [comment]
Works properly now for currency
