### ISSUE TITLE
use TAPI

### ISSUE THREAD

**Issue by starlessboi** [Telaxus/EPESI#114]
hi,thanks for your product
I have a question. do you support and use TAPI in your CRM?
thanks in advance

**Comment by shacky** [comment]
Hi,
do you mean Telephony Application Programming Interface?
I don't think so... it's windows API and Epesi is cross platform 
PHP/MySQL application which runs usually in linux env. We've got some 
asterisk module, but it's not TAPI :)

Best Regards,
Pawel

W dniu 30.08.2016 o 15:00, Mohammad pisze:

**Comment by starlessboi** [comment]
I mean that, too ;)
TAPI or alternatives..
thanks, I got my answer
