### ISSUE TITLE
Help functionality with REDUCING_TRANSFER off

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#120]
Help functionality does not work correctly  when `REDUCING_TRANSFER ` is switched off.
The DOM elements are being replaced and the ones associated in the `Base_Help` javascript object properties (`comment_frame`, `help_arrow`, etc) are not available in the DOM.

**Comment by bukowskiadam** [comment]
Help functionality is somehow abandoned. It's never been developed. We'll get rid of it with upcoming bootstrap release.

**Comment by georgehristov** [comment]
Actually I find it very very useful :)
But of course it is up to you...
