### ISSUE TITLE
ModuleLoader when `FORCE_CACHE_COMMON_FILES` enabled

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#122]
When `FORCE_CACHE_COMMON_FILES` is enabled EPESI throws  `Cannot declare class.., because the name is already in use in...` fatal error when using admin tools: Patches or Run PHP command
##

**Comment by jtylek** [comment]
We should stop using **Common Cache** method completely. It was created specifically for Windows platform as this OS does not limit file searches to paths specifies in php.ini but searches everywhere - including _Windows, System32 etc._ Common Cache was caching all common methods from installed modules into a single file greatly reducing read and seek operations on Windows. On Linux this is not a problem.

If you want to you can remove any code associated with it.

**Comment by jtylek** [comment]
The project is no longer maintained and it was moved to: https://github.com/jtylek/Epesi
