### ISSUE TITLE
Editing select field gives an issue with cols

### ISSUE THREAD

**Issue by bukowskiadam** [Telaxus/EPESI#125]
![image](https://cloud.githubusercontent.com/assets/1633333/19678624/cb5220e6-9a9e-11e6-8b6c-f9a6c77c236f.png)

@georgehristov 
Do you think that we could return field *names* not identifiers from `decode_select_param`?

It would solve the issue. I've reviewed all code and it seems that every place that uses `'cols'` applies `get_field_id`.

Replace
```
$cols = isset($reference[1]) ? array_map(array('Utils_RecordBrowserCommon', 'get_field_id'), array_filter(explode('|', $reference[1]))): null;
```
with
```
$cols = isset($reference[1]) ? array_filter(explode('|', $reference[1])) : null;
```

**Comment by georgehristov** [comment]
I believe it should work as `cols` is used in `Utils_RecordBrowserCommon::create_linked_label` and there the conversion to field ids is also done as a precaution
