### ISSUE TITLE
Problem running composer

### ISSUE THREAD

**Issue by jtylek** [Telaxus/EPESI#126]
Problem 1
    - The requested package bower-asset/gentelella could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by shacky** [comment]
Please read README... you have to run:
composer global require "fxp/composer-asset-plugin:~1.2"
before composer install
