### ISSUE TITLE
Unable to install EPESI - invalid cache path

### ISSUE THREAD

**Issue by pjedwabny** [Telaxus/EPESI#130]
When some entries is being created first time, there is no cache folder, so vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/PathSeekerTrait.php:104 (realpath) returns false, so \phpFastCache\Core\PathSeekerTrait::getFilePath gets path "/files" and tries to write there. Ends with "PLEASE CHMOD - 511 OR ANY WRITABLE PERMISSION!".

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39017741-unable-to-install-epesi-invalid-cache-path?utm_campaign=plugin&utm_content=tracker%2F680206&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F680206&utm_medium=issues&utm_source=github)

**Comment by bukowskiadam** [comment]
known issue ;)
https://github.com/PHPSocialNetwork/phpfastcache/issues/373

**Comment by Geolim4** [comment]
Which should be now resolved ;)
Thanks @bukowskiadam !
