### ISSUE TITLE
Provide 'grant' and 'restrict' functionality from access callbacks

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#133]
The access callback function should return two sets of crits. One to grant access, one to restrict access merged with and. Each callback should have its own type (grant/restrict) stored in database.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39209426-provide-grant-and-restrict-functionality-from-access-callbacks?utm_campaign=plugin&utm_content=tracker%2F680206&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F680206&utm_medium=issues&utm_source=github).

**Comment by bukowskiadam** [comment]
So you're going to change default behavior that's right now. Because now crits are treated as `restrict` option :wink: It may break system preferences after update of the core. I agree that we could use array type return, with fallback mode, but I would prefer to make it backward compatible.

**Comment by georgehristov** [comment]
Ok, this is no issue at all. I will set the 'restrict' option as default to be backward compatible.
