### ISSUE TITLE
phpFastCache error

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#139]
I get below error message when using the new cache engine on the production server (Debian Wheezy).
There are no issues on my test machine (Windows 8.1 Pro)

Any ideas to what might be the cause?

```
InvalidArgumentException
Message: $expiration must be an object implementing the DateTimeInterface
File: /var/www/EPESI/vendor/phpfastcache/phpfastcache/src/phpFastCache/Cache/ItemBaseTrait.php
Line=134
error backtrace:
File: /var/www/EPESI/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/StandardPsr6StructureTrait.php
    line 64
    function called: expiresAt(Object (DateTime))

File: /var/www/EPESI/include/cache.php
    line 52
    function called: getItem("epesi_f533f41c3b2e0c7b7197b75ca6a04ef4_composer_autoloads")

File: /var/www/EPESI/include/module_manager.php
    line 828
    function called: get("composer_autoloads")

File: /var/www/EPESI/include/epesi.php
    line 276
    function called: load_modules()

File: /var/www/EPESI/process.php
    line 41
    function called: process("", "0")
```

**Comment by bukowskiadam** [comment]
Does your server runs PHP 5.4? I've overlooked phpfastcache PHP version requirement, because [DateTimeInterface](http://php.net/manual/en/class.datetimeinterface.php) requires 5.5.

**Comment by georgehristov** [comment]
That's it. I have PHP 5.4.45 on the production server and PHP 7.0.8 on the testing...

**Comment by bukowskiadam** [comment]
v1.8.1.1 reverts cache engine to the old one and fixes the issue. Downloads will be ready in a couple of minutes.

**Comment by georgehristov** [comment]
No problem for me, I did the revert myself but it was good that you amended the release.
