### ISSUE TITLE
SESSION_TYPE memcache reload delay

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#145]
When using the `memcache` option for the SESSION_TYPE I get delay of abt 30 sec when session has expired and login screen needs to be displayed again.
There is no such delay when using the `file` option.

Any idea what might cause this?

**Comment by NorbertNader** [comment]
Bump.
I did find this article though http://rommelsantor.com/clog/2016/02/02/30-second-delay-php-memcache-sessions/
It seems this might occur when memcache.lock_timeout is set to 15 seconds, as that is the default value.
Hope this helps.

**Comment by shacky** [comment]
Great Norbert!
for memcached please set in php.ini:
memcached.sess_lock_wait=1000
or disable memcached.sess_locking.
We can close it.

**Comment by georgehristov** [comment]
First of all thanks to @NorbertNader for the support.
Actually I tested reducing `memcached.sess_lock_wait` first but problem persisted. Anyway default is 150000 ms which is 150 s and does not match the description in the post.
Now I am playing with `memcached.sess_lock_expire` and `memcached.sess_lock_max_wait` which finally default to php `max_execution_time`: in my case it matches the observed delay time of 30 sec.
Will revert with outcome...

**Comment by georgehristov** [comment]
Looks like in the source I was checking `memcached.sess_lock_wait` dimension was wrong.
Checking [here](https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini) it is mentioned a microseconds so default is 0.15 s. In Any case it is definitely not the setting to change.
I have played with `memcached.sess_lock_expire` and `memcached.sess_lock_max_wait` but without success so far.

**Comment by georgehristov** [comment]
I have exhausted all options with php-memcached settings and the issue was not resolved.

I believe now it has something to do with [this](https://github.com/Telaxus/EPESI/blob/testing/include/session.php#L53) code in EPESI

**Comment by georgehristov** [comment]
Any particular reason why [this](https://github.com/Telaxus/EPESI/blob/testing/process.php#L32) is commented out?
When main session expires I get the 30 s delay because destroy method is not called

**Comment by georgehristov** [comment]
When this line enabled the system immediately redirects but waits 30 s at the index.php and then proceeds to login screen

**Comment by bukowskiadam** [comment]
Please try after last changes

**Comment by georgehristov** [comment]
Thank you, I updated the code, will revert after testing

**Comment by georgehristov** [comment]
Now it works proper, thank you!
