### ISSUE TITLE
company contact field - crits issues

### ISSUE THREAD

**Issue by bukowskiadam** [Telaxus/EPESI#152]
Clean installations with company contact field (e.g. Task - Customers) have crits callback set, but updated installation with [patch](https://github.com/Telaxus/EPESI/blob/v1.8.0/modules/CRM/Contacts/patches/20160705_rewrite_all_company_contact_fields.php) does not. In Tasks [customer_crits](https://github.com/Telaxus/EPESI/blob/v1.8.0/modules/CRM/Tasks/TasksCommon_0.php#L130) does not make sense - they allow to choose only from recent or favorite contacts/companies.

We have to review all crits callbacks for company/contact field.

**Comment by jtylek** [comment]
The project is no longer maintained and it was moved to: https://github.com/jtylek/Epesi
