### ISSUE TITLE
phpfastcache call to undefined apc_fetch() for PHP7

### ISSUE THREAD

**Issue by NorbertNader** [Telaxus/EPESI#173]
Call to undefined function phpFastCache\Drivers\Apcu\apc_fetch()

This requires to install [apcu_bc](https://pecl.php.net/package/apcu_bc) alongside APCu for backwards compatibility with APC.

**Comment by shacky** [comment]
Can you provide backtrace? Apcu driver uses apcu_fetch instead of apc_fetch... Should work with plain apcu - i've got php 7.0.17 + apcu 5.1.8-1.fc25 and it works fine.

**Comment by NorbertNader** [comment]
Thanks for the hint. This was indeed caused by APC as it was also loaded alongside APCu after installing apcu_bc.
