### ISSUE TITLE
Memcached session ends

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#181]
When using `memcache` option for storing session data clicking on any of the action bar buttons under Module Administration pops message "Session expired, restarting EPESI".
No error messages in browser or in error log.

When using `file` option all is working fine.

Server Installation:
EPESI 1.8.2
Debian 8.6
PHP 5.6.28
memcached 1.4.21-1.1+deb8u1
php5-memcached 2.2.0-2

**Comment by NorbertNader** [comment]
I am not sure what you are referring to. I have php7.1.4 with memcached 3.0.3 and I am not encountering any issue. 

So you can not access any module from menu->administrator?

**Comment by georgehristov** [comment]
I can access the Admin area and all options. But when under Module Administration whichever button I click on the ActionBar I get the "Session expired, restarting EPESI" message.

**Comment by NorbertNader** [comment]
I actually ran into a similar issue today and had to restart memcached. Did you try doing that?

**Comment by jtylek** [comment]
The project is no longer maintained and it was moved to: https://github.com/jtylek/Epesi
