### ISSUE TITLE
RB no columns displayed when no records

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#183]
No GenericBrowser columns displayed if the list is empty (no rows).
This is caused by the new column access functionality.

If the `enable_quick_new_records` option is used then no new records can be added if list is empty as only save button is displayed (no fields).

**Comment by NorbertNader** [comment]
Closed with fd442e8363f3eb8301fa42f5bebbec74543718aa

**Comment by georgehristov** [comment]
I believe I fixed it with still with d11f8b648
