### ISSUE TITLE
Scripts missing on refresh

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#194]
Very strange case where I get jscript terminal error on refreshing the page so page goes blank.

The error is related to scripts not loaded, first one is `rb_indexer` not found.
if I add existence check then `shortcut.remove_all()` is not found

version 1.8.2

**Comment by NorbertNader** [comment]
I can't seem to produce this error, does this happen to you randomly or in a specific case?

**Comment by georgehristov** [comment]
It happens randomly when refreshing the EPESI page. The loading logo appears briefly and then all goes blank because jscript has failed with error on missing functions.
If it happens I need to refresh 3-4 times and at one point it starts. There are no further issues when using the system.

**Comment by georgehristov** [comment]
Problem disappeared after deleting the data/cache folder contents
