### ISSUE TITLE
Webpack doesn't work

### ISSUE THREAD

**Issue by zieba-michal** [Telaxus/EPESI#220]
Like in title, there is a problem with webpack building. I attach npm

**Comment by ZiebaM** [comment]
[npm-list.txt](https://github.com/Telaxus/EPESI/files/1367307/npm-list.txt)

**Comment by pjedwabny** [comment]
Should be fixed by commit d3ed7c20dca90d6877caf7d8f1cb1379bdb48b8c

**Comment by jtylek** [comment]
The project is no longer maintained and it was moved to: https://github.com/jtylek/Epesi
