### ISSUE TITLE
Security - Bugs in libraries

### ISSUE THREAD

**Issue by bpabiszczak** [Telaxus/EPESI#228]
https://unsecure.blog/en/122-dozens-of-security-bugs-in-popular-crm-systems.html

**Comment by bukowskiadam** [comment]
https://github.com/mariuszkrzaczkowski/EPESI_Libraries_Vulnerabilities

?
---

whois unsecure.blog
```
Domain Name: UNSECURE.BLOG
...
Registrant Name: Blazej Pabiszczak
Registrant Organization: YetiForce Sp. z o.o.
```

**Comment by bpabiszczak** [comment]
Nasz druga spółka. Jest tam zakładka kontakt. Choć nie wiem jakie ma to znaczenie.

**Comment by jtylek** [comment]
https://unsecure.blog/en/122-dozens-of-security-bugs-in-popular-crm-systems.html

![image](https://user-images.githubusercontent.com/3438599/61099200-d2630b00-a461-11e9-81f2-123ac119d139.png)

Co to za spamowanie konkurencji?
