### ISSUE TITLE
EPESI and PHP7.2

### ISSUE THREAD

**Issue by BramPeerlings** [Telaxus/EPESI#236]
We've recently upgraded to PHP 7.2, only to find our (self-hosted) EPESI-system not working anymore. I've just installed the latest release from this repository (1.8.2-20180413, by @pjedwabny), but that still does not seem to be compatible. 

Any ideas on how to fix this? Directly using the code in the `master`-branch didn't work either: it seem to be (more) compatible with PHP7.2, but not production-ready.

**Comment by BramPeerlings** [comment]
I have just stumbled upon https://github.com/Telaxus/EPESI/pull/233 and https://forum.epesibim.com/d/5085-errors-with-the-php7-2, but that doesn't seem to be a (complete) fix either.

**Comment by jtylek** [comment]
Unfortunately I also can not get PHP 7.2 to work and had to go back to 7.1
At this time I don't have a time to work on this problem, however I will be refreshing the application and during a rewrite I will  be checking for compatibility problems with 7.2

**Comment by georgehristov** [comment]
Fixed with 2f63597

**Comment by jtylek** [comment]
Thank you! @georgehristov 👍
