### ISSUE TITLE
XAMPP php7.2

### ISSUE THREAD

**Issue by NetLancer** [Telaxus/EPESI#237]
On windows, i'm having an issue installing EPESI.
Has it been tested on latest window xampp environment ?
I mean installation and basic usage.
Moreover, it seems there's no vendor directory existing at all, yet is required by include.php ('vendor/autoload.php', on line 18).
As a result i'm currently getting simply a blank browser page

**Comment by jtylek** [comment]
Yes, it has been tested on Windows under both Ammps and xampp packages:
[https://www.ampps.com/](https://www.ampps.com/)
[https://www.apachefriends.org/index.html](https://www.apachefriends.org/index.html)

The advantage of Ampps is that it utilizes Softaculous autoinstaller. However for debugging (xdebug) XAMPP is easier to configure.

How did  you install Epesi?
If you installed it from Sourceforge [https://sourceforge.net/projects/epesi/](https://sourceforge.net/projects/epesi/) then all vendor directories are included.
However if you install from Github then you need to run composer first, which will populate the vendor's directory.

**Comment by NetLancer** [comment]
xampp on win10

**Comment by jtylek** [comment]
Please check your php log file.

**Comment by NetLancer** [comment]
Thanks a lot jtylek. 
I hope there'll be soon support for latest (stable) php too, 
I really believe epesi's a nice & useful (as well as flexible/extendable) tool and as such will attract contributors and more interest form business folks in the near future.
Thanks & respect to dev guys!

**Comment by georgehristov** [comment]
Fixed with 2f63597
