### ISSUE TITLE
Few thoughts on Epesi use

### ISSUE THREAD

**Issue by NetLancer** [Telaxus/EPESI#238]
Seems to me the platform lacks examples pages on usage & some customization things. 
Even existing videos (youtube) are more about installation & basics and are a bit obsolete, though i'm sure there'll be more engagement and contribution to the product in future.
I've fetched a while for this sort of platform (Enterprise, browser-view, data-oriented, flexible, easily extendable, stable and well-maintained apart from being opensource) and i finally come to know epesi which seemed to be closest to my desired params.
Right now i'm working on an app which also need feature like
dependent drop-downs. 
I'm studying epesi documentation and seemingly that feature (above) to be made via framework API.
Still, i wish there would be more articles, videos on epesi features, advanced usage with real world examples.
Thanks a lot.

**Comment by EmanuelaY** [comment]
Thank you for considering epesi as your choice for building web application.

You can find more detailed documentation on [epesi.org](https://epesi.org/). We’re working on new documentation but our resources are limited. We’re also running a forum where you can find some answers- [forum.epesibim.com](https://forum.epesibim.com/). 

As for “depending drop-downs”- also called **change select** is used in common data ([epesi.org/commondata](https://epesi.org/commondata)) I think that these materials will be helpful:
[forum.epesibim.com/chained-select](https://forum.epesibim.com/d/4099-chained-select-in-libs-quickform/2)
[www.jqueryscript.net/Simple-jQuery-Plugin-For-Chained-Selects-Chained.html](https://www.jqueryscript.net/form/Simple-jQuery-Plugin-For-Chained-Selects-Chained.html) 
CRM companies module is using this feature in fields of country and zones.

**Comment by jtylek** [comment]
Here are screenshots from CRM Companies module showing chained-select fields: Countries and Zones:

![image](https://user-images.githubusercontent.com/3438599/54955952-1253c000-4f4f-11e9-9670-18721b0eba45.png)

when Poland is selected the chained field zone automatically loads necessary values if they exist:
![image](https://user-images.githubusercontent.com/3438599/54955993-34e5d900-4f4f-11e9-9ab8-423390677d79.png)

**Comment by jtylek** [comment]
https://github.com/Telaxus/EPESI/issues/241
