### ISSUE TITLE
This project is no longer maintained.

### ISSUE THREAD

**Issue by bpabiszczak** [Telaxus/EPESI#241]
Coś więcej można o tym przeczytać?

**Comment by georgehristov** [comment]
Project moved to this repository for further development: https://github.com/jtylek/Epesi

**Comment by bpabiszczak** [comment]
to widzę, ale z ciekawości dlaczego z firmowego przerzucacie na prywatne konto?

**Comment by jtylek** [comment]
English please. We are on Github,
Telaxus LLC which I created in 2006 for development of Epesi is being closed in USA. Therefore I take the project under my personal control, as Epesi is my creation and extension of my experience with other open source web applications and especially my own, in-house developed Maximus CRM written unfortunately in ASP.
You can read the story here: https://en.wikipedia.org/wiki/Epesi
