### ISSUE TITLE
Base/Notify - performance issues for Watchdog

### ISSUE THREAD

**Issue by bukowskiadam** [Telaxus/EPESI#31]
Watchdog handler for notifications gets all events and prepares changes list for every, what takes a lot of time. During this time session is locked, because notify's refresh script requires write permission to the session. In case when user has a lot of pending notifications EPESI operation is very slow.

I suggest to change watchdog notifications to show only number of pending notifications. Maybe show the number by category - e.g. Contacts - 1 change, Notes - 4 changes, etc.

**Comment by bukowskiadam** [comment]
Now I see that even grouping by category may be a huge slowdown or may lead to wrong message count. Record permissions are check during events display. If you don't have rights to some record then event won't be shown. Now even in applet you can get wrong number of total notifications, but I don't see any fast(in term of processing time) solution to fix this number.
I've changed to show info, that you've got some unread notifications - nothing more. Please review my changes aebe608140bde23cf520fcb9a6d6428264d79555

**Comment by georgehristov** [comment]
I have completely rewritten the Base/Notify module to avoid locking the session. I will test is just a bit more and create a pull request for the new version.

**Comment by bukowskiadam** [comment]
Locking the session is the reason for the visible performance, as it blocks other requests. However watchdog notifications can generate huge overload of the server (if you wish to revert them as they was before my changes). I'm waiting for the new version of your module and we'll discuss it later.

**Comment by georgehristov** [comment]
I believe this issue can be closed following the re-work on the Base/Notify module?

**Comment by bukowskiadam** [comment]
You're right
