### ISSUE TITLE
Utils_RecordBrowser does not add "id" attribute to "commondata" select elements 

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#36]
"id" is included in the list of parameters for the form element under Utils_RecordBrowserCommon::QFfield_commondata but the select does not have an "id" attribute.

**Comment by bukowskiadam** [comment]
Thanks for reporting this. It'll be fixed asap I'll do push. id attribute has been put into wrong argument. Here is the proper way:

    $form->addElement($desc['type'], $field, $label, $param, array('empty_option' => true, 'order_by_key' => $desc['param']['order_by_key']), array('id' => $field));

**Comment by georgehristov** [comment]
Great, thanks!
