### ISSUE TITLE
Missing php end tag

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#40]
php end tag is missing in Base/AdminCommon_0.php file which causes fatal when enabling FORCE_CACHE_COMMON_FILES

**Comment by bukowskiadam** [comment]
Thanks. Fixed

**Comment by georgehristov** [comment]
You should check also the Premium modules (I have: Free + Import), there was an issue with 1 or 2 files there as well but I do not remember now which ones.
