### ISSUE TITLE
Utils_CommonData nodes sorting with RB chained select

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#42]
Utils_CommonData update.php script does not return the nodes sorted as per RB setting (sort_by_key for instance) when using a commondata chained select fields in RB.

**Comment by bukowskiadam** [comment]
I've fixed this. Also I've improved RB admin gui to allow select order type. Please review and test if you wish.

**Comment by georgehristov** [comment]
Great! I have tested and GUI seems to work fine. There is only one thing that needs to be completed in regard to the commondata positioning: sorting in GenericBrowser when browsing records.
Presently if using the sort option of a commondata column data is sorted only in alphabetical order. I saw that values are retrieved by SQL (I do not remember the exact method) and it requires a bit of refactoring to retrieve the position and add it as "order value" in the GB row. I did not have time to work on that....

**Comment by bukowskiadam** [comment]
I was trying to do this, but it's too complicated, because of translations and chained commondata (like zone). It will always work for key order. For position sort it won't work for chained selects. For value it won't translate value.

**Comment by georgehristov** [comment]
Yes, it was too complicated and that's why I did not pop up the topic when I noticed.
And on second thought it would not be intuitive if it is sorted by position...

**Comment by bukowskiadam** [comment]
I've made some commits - please review them if you wish. Any comments are welcome.
