### ISSUE TITLE
confirmLeave detecting a changed value in forms where ChainedSelects are present

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#44]
When adding / editing a record with chained selects the update script of the chained selects triggers "change" event and causes the relevant fields to be marked with "changed-input" class although user has not changed anything.
Script requires confirmation even if no user changes done on the form.

**Comment by bukowskiadam** [comment]
Editing contacts works properly (with zone field select).

**Comment by georgehristov** [comment]
The contacts has CommonData chained select and there the problem is a bit different.
Please check RB recordset with ChainedSelect where custom list is returned (edit an existing Phonecall and just click cancel)

Not sure at the moment why but the failure in CommonData chained select appears in such sequence:
- edit an existing record (change country or zone) and save
- click edit again and just click cancel (without changing anything)
