### ISSUE TITLE
RecordBrowser_RecordPicker pops confirmLeave dialog when browsing pages

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#54]
In edit mode of a record having a single tab multiselect field where RecordBrowser_RecordPicker is available a confirmLeave message appears in case one of the record edit form fields changed and user tries to browse between pages on the RecordPicker

**Comment by georgehristov** [comment]
Fixed with commit 5b677ca

**Comment by bukowskiadam** [comment]
I've got some other issues with RecordPicker - sometimes switching pages doesn't work, sometimes it doesn't fill the original field with value. I'll testing this right now.

**Comment by georgehristov** [comment]
I also have issues but it might be due to my code: when entering search string nothing changes and then I cannot change pages. When I close the Leightbox, I cannot open again.
But as said I am using a custom QFfield callback for the select field which changes the param \_\_RECORDSETS\_\_ to a specific tab depending on a hidden field so this might be my problem. I have not gone deeper on that yet.
When I implement RecordPicker the standard way I have not experienced issues (after your fix).

**Comment by bukowskiadam** [comment]
I've got the same issue with paging and opening sometimes.

Values are filled into multiselect but with no labels. Inspect checkbox in the recordpicker - it should have  formated_name attribute, but it's not properly generated so it fills with empty string. I'm working on that.
