### ISSUE TITLE
Utils_RecordBrowserCommon::create_linked_label_r does not transform record values

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#56]
The values of the record passed to Utils_RecordBrowserCommon::create_linked_label_r are not transformed to display values (for commondata, etc).
I believe this is not how it is intended.

**Comment by bukowskiadam** [comment]
Indeed it could be, but now calling `get_val` will lead to infinite recursion. RB calls `get_val` for each field, that field's display callback calls `create_linked_label_r` which would call get_val again. E.g. display_fname in contacts.

**Comment by georgehristov** [comment]
yes, I became aware about this when implementing the b1ce99c a few hours after posting this issue.
