### ISSUE TITLE
Linked label does not work /in specific sequence/

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#57]
When used in following sequence the jump to record link does not work:
- Menu: CRM: Contacts
- click on the link of any contact company
- on the contacts addon click to view contact record
- in contact record "view" mode when the company name is clicked the link is not followed, only toolbar buttons change to those for company "view" mode

**Comment by bukowskiadam** [comment]
Your commit b1e7b4f0d7fe3cf5877590f5a1b760605ad09be4 introduced this bug... what do you think we should do now?

**Comment by georgehristov** [comment]
Actually first thing I did was to revert that commit and test and same bug appeared but maybe I did a mistake. Now when I reverted, bug is gone.
I will look into it.
