### ISSUE TITLE
Browse view not displaying properly when using recursive access rules on select field

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#63]
RecordBrowser browse pages and total number of records are not displayed properly when using a recursive access setting on a select field.

**Comment by bukowskiadam** [comment]
We know about that, but it's really complex issue. Currently those access rules are checked with PHP code, not database queries, so we're unable to properly count records, because of performance issues it will cause.
Won't be fixed right now, but we'd like to address this issue.

**Comment by georgehristov** [comment]
Is it not better to keep this open so it is clear this is a known issue?

**Comment by bukowskiadam** [comment]
Yes - you're right. My bad :wink:

**Comment by bukowskiadam** [comment]
I suppose we can close this issue, as in most cases problem has been fixed. Currently only ACCESS_X_ALL will cause issue as we are unable to create such SQL query.

**Comment by georgehristov** [comment]
Yes, it has been running seamlessly on our production server for some time already.
I noticed in commit a1f4029b72f4 you refer to this as well but have not pulled it / tested yet.
I presume the functionality introduced here will not be lost after a1f4029b72f4 if you want to close this issue?

**Comment by bukowskiadam** [comment]
Not at all. Just it looks that subquery execution seems to be faster for several conditions than several joins.

**Comment by georgehristov** [comment]
Clear, so we can close this..
