### ISSUE TITLE
RB browse mode search and apply filters act separately [$50]

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#70]
The "Show" button for applying the RB filters and "Search" button act separately which is not intuitive.
If an user searches for a word and then changes the filters then he has to click on "Show" first and then  "Search".
If user clicks on "Search" button only then the modified filter values are visible in the fields but filters are not actually applied.
##

**Comment by bukowskiadam** [comment]
It could be considered as a bug, but in fact those forms are two different ones so I've assigned enhancement. We'll take care about that in the future.

**Comment by jtylek** [comment]
The project is no longer maintained and it was moved to: https://github.com/jtylek/Epesi
