### ISSUE TITLE
RB edit mode form errors not displayed

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#95]
The form error messages are not displayed. When trying to safe a record without entering some required field for instance.
Appears on the current dev version.

**Comment by bukowskiadam** [comment]
Works for me (add new contact -> save without filling -> first name, last name required). Try to rebuild theme in the `/admin` panel.

**Comment by georgehristov** [comment]
I did so twice but it did not work. Will check again.

**Comment by georgehristov** [comment]
Just tried again - looks like problem is specifically on the Phonecalls editing.

**Comment by bukowskiadam** [comment]
The only error I see is that phone nr error does not have the close button
![image](https://cloud.githubusercontent.com/assets/1633333/16796180/8cf40fda-48e1-11e6-9cb2-ff884f90891a.png)

**Comment by georgehristov** [comment]
The problem is caused by the JS function `enable_disable_customer` declared within `CRM_PhoneCallCommon::QFfield_other_contact`. When customers are only few - the `customer__search` input is not existing and JS throws error `Uncaught TypeError: Cannot set property 'disabled' of undefined`.
I think this part needs a rewrite - especially there is a TODO comment: rewrite to jQuery :)
